services:
  config-server:
    image: ${IMAGE_REGISTRY:-ghcr.io}/${IMAGE_NAMESPACE:-taukhir/shopverse}/config-server:${IMAGE_TAG:-latest}

  discovery-server:
    image: ${IMAGE_REGISTRY:-ghcr.io}/${IMAGE_NAMESPACE:-taukhir/shopverse}/discovery-server:${IMAGE_TAG:-latest}

  user-service:
    image: ${IMAGE_REGISTRY:-ghcr.io}/${IMAGE_NAMESPACE:-taukhir/shopverse}/user-service:${IMAGE_TAG:-latest}

  auth-service:
    image: ${IMAGE_REGISTRY:-ghcr.io}/${IMAGE_NAMESPACE:-taukhir/shopverse}/auth-service:${IMAGE_TAG:-latest}

  order-service:
    image: ${IMAGE_REGISTRY:-ghcr.io}/${IMAGE_NAMESPACE:-taukhir/shopverse}/order-service:${IMAGE_TAG:-latest}

  payment-service:
    image: ${IMAGE_REGISTRY:-ghcr.io}/${IMAGE_NAMESPACE:-taukhir/shopverse}/payment-service:${IMAGE_TAG:-latest}

  inventory-service:
    image: ${IMAGE_REGISTRY:-ghcr.io}/${IMAGE_NAMESPACE:-taukhir/shopverse}/inventory-service:${IMAGE_TAG:-latest}

  api-gateway:
    image: ${IMAGE_REGISTRY:-ghcr.io}/${IMAGE_NAMESPACE:-taukhir/shopverse}/api-gateway:${IMAGE_TAG:-latest}
