global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
        labels:
          application: prometheus

  - job_name: shopverse-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - api-gateway:8080
        labels:
          application: API-GATEWAY
      - targets:
          - auth-service:8081
        labels:
          application: AUTH-SERVICE
      - targets:
          - user-service:8082
        labels:
          application: USER-SERVICE
      - targets:
          - order-service:8083
        labels:
          application: ORDER-SERVICE
      - targets:
          - payment-service:8084
        labels:
          application: PAYMENT-SERVICE
      - targets:
          - inventory-service:8086
        labels:
          application: INVENTORY-SERVICE
      - targets:
          - discovery-server:8761
        labels:
          application: DISCOVERY-SERVER
      - targets:
          - config-server:8888
        labels:
          application: CONFIG-SERVER
