global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
        labels:
          application: prometheus

  - job_name: shopverse-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
        labels:
          application: API-GATEWAY
      - targets:
          - host.docker.internal:8081
        labels:
          application: AUTH-SERVICE
      - targets:
          - host.docker.internal:8082
        labels:
          application: USER-SERVICE
      - targets:
          - host.docker.internal:8083
        labels:
          application: ORDER-SERVICE
      - targets:
          - host.docker.internal:8761
        labels:
          application: DISCOVERY-SERVER
      - targets:
          - host.docker.internal:8888
        labels:
          application: CONFIG-SERVER
