package io.shopverse.order.entity;

public enum OrderStatus {
    ORDER_CREATED,
    PENDING_INVENTORY,
    INVENTORY_RESERVED,
    PAYMENT_PROCESSING,
    INVENTORY_REJECTED,
    PAYMENT_FAILED,
    CONFIRMED,
    CANCELLED,
    PACKING,
    SHIPPED,
    OUT_FOR_DELIVERY,
    DELIVERED,
    RETURN_REQUESTED,
    RETURNED
}
