server:
  port: ${SERVER_PORT:8081}

security:
  jwt:
    issuer: ${JWT_ISSUER:shopverse-auth-service}

spring:
  cloud:
    openfeign:
      client:
        config:
          USER-SERVICE:
            connect-timeout: ${USER_SERVICE_CONNECT_TIMEOUT:2000}
            read-timeout: ${USER_SERVICE_READ_TIMEOUT:3000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,refresh
