server:
  port: ${SERVER_PORT:8084}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8081/auth/.well-known/jwks.json}

shopverse:
  payment-service:
    health-checkup:
      message: ${PAYMENT_SERVICE_HEALTH_CHECKUP_MESSAGE:Payment service is running}
