[CmdletBinding()]
param(
    [string]$GatewayUrl = "http://localhost:8080",
    [string]$AdminUsername = "admin",
    [string]$AdminPassword = $env:SHOPVERSE_ADMIN_PASSWORD,
    [ValidateRange(1, 20)]
    [int]$CustomerCount = 20,
    [ValidateRange(1, 20)]
    [int]$ProductCount = 20,
    [ValidateRange(1, 500)]
    [int]$OrderCount = 50,
    [ValidateRange(1, 8)]
    [int]$BatchSize = 4,
    [ValidateRange(5, 60)]
    [int]$RequestTimeoutSeconds = 20,
    [ValidateRange(30, 300)]
    [int]$BatchTimeoutSeconds = 120,
    [string]$CustomerPassword = "Shopverse!2026",
    [string]$CredentialsPath = "",
    [string]$ManifestPath = ""
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$repositoryRoot = Split-Path -Parent $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($CredentialsPath)) {
    $CredentialsPath = Join-Path $repositoryRoot "shopverse-local-credentials.md"
}
if ([string]::IsNullOrWhiteSpace($ManifestPath)) {
    $ManifestPath = Join-Path $repositoryRoot ".tmp/shopverse-api-seed-manifest.json"
}

function Get-HttpStatusCode {
    param([System.Management.Automation.ErrorRecord]$ErrorRecord)

    if ($null -eq $ErrorRecord.Exception.Response) {
        return 0
    }

    return [int]$ErrorRecord.Exception.Response.StatusCode
}

function Invoke-ShopverseJson {
    param(
        [ValidateSet("Get", "Post", "Put")]
        [string]$Method,
        [string]$Uri,
        [hashtable]$Headers,
        [object]$Body,
        [int]$TimeoutSeconds,
        [int[]]$RetryStatusCodes = @(429, 502, 503, 504)
    )

    $jsonBody = if ($null -eq $Body) { $null } else { $Body | ConvertTo-Json -Depth 8 -Compress }

    for ($attempt = 1; $attempt -le 4; $attempt++) {
        try {
            $parameters = @{
                Method = $Method
                Uri = $Uri
                Headers = $Headers
                TimeoutSec = $TimeoutSeconds
                ErrorAction = "Stop"
            }
            if ($null -ne $jsonBody) {
                $parameters.ContentType = "application/json"
                $parameters.Body = $jsonBody
            }
            return Invoke-RestMethod @parameters
        } catch {
            $statusCode = Get-HttpStatusCode $_
            if ($attempt -eq 4 -or $statusCode -notin $RetryStatusCodes) {
                throw
            }
            Start-Sleep -Milliseconds (250 * $attempt)
        }
    }
}

function Get-AccessToken {
    param(
        [string]$Username,
        [string]$Password
    )

    $login = Invoke-ShopverseJson `
        -Method Post `
        -Uri "$GatewayUrl/auth/login" `
        -Headers @{} `
        -Body @{ username = $Username; password = $Password } `
        -TimeoutSeconds $RequestTimeoutSeconds

    if ([string]::IsNullOrWhiteSpace($login.token)) {
        throw "Login for '$Username' did not return an access token."
    }

    return $login.token
}

function Update-GeneratedCredentials {
    param(
        [object[]]$Customers
    )

    $directory = Split-Path -Parent $CredentialsPath
    if (-not [string]::IsNullOrWhiteSpace($directory)) {
        New-Item -ItemType Directory -Force -Path $directory | Out-Null
    }

    $startMarker = "<!-- SHOPVERSE-API-SEED-START -->"
    $endMarker = "<!-- SHOPVERSE-API-SEED-END -->"
    $rows = @($Customers | ForEach-Object {
        "| $($_.Username) | $($_.FirstName) $($_.LastName) | $CustomerPassword | ROLE_CUSTOMER |"
    })
    $sectionLines = @(
        $startMarker,
        "",
        "## API Seeded Customer Accounts",
        "",
        "Generated by scripts/Seed-ShopverseData.ps1 for local development and verification.",
        "",
        "| Username | Name | Password | Role |",
        "| --- | --- | --- | --- |"
    )
    $sectionLines += $rows
    $sectionLines += @(
        "",
        "Administrator used by this run: $AdminUsername.",
        $endMarker
    )
    $section = $sectionLines -join [Environment]::NewLine

    $current = if (Test-Path -LiteralPath $CredentialsPath) {
        Get-Content -LiteralPath $CredentialsPath -Raw
    } else {
        @(
            "# Shopverse Local Credentials",
            "",
            "This file is intentionally ignored by Git. These accounts are only for the",
            "local Shopverse development and verification environment.",
            "",
            "| Account | Username | Password | Role |",
            "|---|---|---|---|",
            "| Administrator | ``admin`` | ``Admin@123`` | ``ROLE_ADMIN`` |",
            "| Customer One | ``customer1`` | ``Customer@123`` | ``ROLE_CUSTOMER`` |",
            "| Customer Two | ``customer2`` | ``Buyer@123`` | ``ROLE_CUSTOMER`` |",
            "",
            "## Local Ecosystem Credentials",
            "",
            "These values mirror the ignored root ``.env`` file for the local Shopverse stack.",
            "",
            "| System | URL | Username | Password / Secret |",
            "|---|---|---|---|",
            "| MySQL root | ``localhost:3307`` | ``root`` | ``root`` |",
            "| MySQL service user | ``localhost:3307`` | ``ahmed`` | ``Ahm3d@123`` |",
            "| MinIO API | ``http://localhost:9000`` | ``shopverse-minio`` | ``ShopverseMinio@2026`` |",
            "| MinIO Console | ``http://localhost:9001`` | ``shopverse-minio`` | ``ShopverseMinio@2026`` |",
            "| Docker Compose project | local Docker Desktop | n/a | uses local Docker context |",
            "| Kafka broker | ``localhost:9092`` | n/a | no local authentication |",
            "| Grafana | ``http://localhost:3000`` | ``admin`` | ``admin`` |",
            "| Jenkins | ``http://localhost:8085`` | ``admin`` | ``admin`` |",
            "| Zipkin | ``http://localhost:9411`` | n/a | no local authentication |",
            "| Prometheus | ``http://localhost:9090`` | n/a | no local authentication |",
            "| Loki | ``http://localhost:3100`` | n/a | no local authentication |",
            "| Eureka | ``http://localhost:8761`` | n/a | no local authentication |",
            "| Config Server | ``http://localhost:8888`` | n/a | no local authentication |",
            "",
            "## Local Application URLs",
            "",
            "| Interface | URL |",
            "|---|---|",
            "| Angular storefront/admin | ``http://localhost:4200`` |",
            "| Documentation | ``http://localhost:3001`` |",
            "| API Gateway | ``http://localhost:8080`` |",
            "",
            "The customer passwords are stored in MySQL as delegated BCrypt hashes. The",
            "plaintext values exist only in this ignored local reference.",
            "",
            "Production environments must use adaptive password hashing such as BCrypt or",
            "Argon2 and must store credentials in a managed secret system.",
            ""
        ) -join [Environment]::NewLine
    }

    $current = $current.
        Replace("# Shopverse Local Demo Credentials", "# Shopverse Local Credentials").
        Replace("local Shopverse POC.", "local Shopverse development and verification environment.").
        Replace("These values mirror the ignored root `.env` file for the local Shopverse development and verification environment.", "These values mirror the ignored root `.env` file for the local Shopverse stack.")

    $pattern = "(?s)" + [regex]::Escape($startMarker) + ".*?" + [regex]::Escape($endMarker)
    $updated = if ($current -match $pattern) {
        [regex]::Replace($current, $pattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($match) $section })
    } else {
        $current.TrimEnd() + [Environment]::NewLine + [Environment]::NewLine + $section + [Environment]::NewLine
    }

    Set-Content -LiteralPath $CredentialsPath -Value $updated -Encoding utf8
}

if ([string]::IsNullOrWhiteSpace($AdminPassword)) {
    $securePassword = Read-Host "Enter the password for $AdminUsername" -AsSecureString
    $pointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($securePassword)
    try {
        $AdminPassword = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($pointer)
    } finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($pointer)
    }
}

$customers = @(
    [pscustomobject]@{ Username = "john.smith"; FirstName = "John"; LastName = "Smith" },
    [pscustomobject]@{ Username = "emily.johnson"; FirstName = "Emily"; LastName = "Johnson" },
    [pscustomobject]@{ Username = "michael.brown"; FirstName = "Michael"; LastName = "Brown" },
    [pscustomobject]@{ Username = "sarah.williams"; FirstName = "Sarah"; LastName = "Williams" },
    [pscustomobject]@{ Username = "david.jones"; FirstName = "David"; LastName = "Jones" },
    [pscustomobject]@{ Username = "jessica.garcia"; FirstName = "Jessica"; LastName = "Garcia" },
    [pscustomobject]@{ Username = "daniel.miller"; FirstName = "Daniel"; LastName = "Miller" },
    [pscustomobject]@{ Username = "laura.davis"; FirstName = "Laura"; LastName = "Davis" },
    [pscustomobject]@{ Username = "robert.martinez"; FirstName = "Robert"; LastName = "Martinez" },
    [pscustomobject]@{ Username = "amanda.wilson"; FirstName = "Amanda"; LastName = "Wilson" },
    [pscustomobject]@{ Username = "christopher.anderson"; FirstName = "Christopher"; LastName = "Anderson" },
    [pscustomobject]@{ Username = "olivia.thomas"; FirstName = "Olivia"; LastName = "Thomas" },
    [pscustomobject]@{ Username = "matthew.taylor"; FirstName = "Matthew"; LastName = "Taylor" },
    [pscustomobject]@{ Username = "sophia.moore"; FirstName = "Sophia"; LastName = "Moore" },
    [pscustomobject]@{ Username = "andrew.jackson"; FirstName = "Andrew"; LastName = "Jackson" },
    [pscustomobject]@{ Username = "natalie.white"; FirstName = "Natalie"; LastName = "White" },
    [pscustomobject]@{ Username = "joshua.harris"; FirstName = "Joshua"; LastName = "Harris" },
    [pscustomobject]@{ Username = "rachel.martin"; FirstName = "Rachel"; LastName = "Martin" },
    [pscustomobject]@{ Username = "kevin.thompson"; FirstName = "Kevin"; LastName = "Thompson" },
    [pscustomobject]@{ Username = "megan.clark"; FirstName = "Megan"; LastName = "Clark" }
) | Select-Object -First $CustomerCount

$catalogGroups = @(
    @{ BasePrice = 49.99; Names = @("Nova Wireless Earbuds", "Orbit Bluetooth Speaker", "Pulse Fitness Tracker", "Lumen Desk Lamp", "Vertex USB-C Hub", "Echo Noise Cancelling Headphones", "Aero Portable Charger", "Pixel Web Camera", "Sonic Mini Soundbar", "Volt Smart Plug", "Atlas Tablet Stand", "Wave Mechanical Keyboard", "Prism Wireless Mouse", "Halo LED Monitor Light", "Core Laptop Sleeve") },
    @{ BasePrice = 12.99; Names = @("Canvas Notebook Set", "Graphite Gel Pen Pack", "Cedar Desk Organizer", "Metro Weekly Planner", "Studio Sticky Notes", "Archive File Folder Set", "Focus Timer", "Summit Document Tray", "Craft Paper Cutter", "Signal Desk Clock", "Nordic Pen Holder", "Drafting Ruler Set", "Slate Mouse Pad", "Vision Whiteboard Kit", "Ledger Expense Journal") },
    @{ BasePrice = 24.99; Names = @("Harbor Throw Pillow", "Willow Storage Basket", "Mason Glass Food Container", "Terrace Plant Pot", "Cove Cotton Towel Set", "Ember Scented Candle", "Meadow Table Runner", "Sierra Ceramic Mug Set", "Solstice Wall Clock", "Hearth Bamboo Cutting Board", "Loft Laundry Basket", "Orchid Bedside Lamp", "Luna Picture Frame", "Birch Serving Tray", "Fern Shower Caddy") },
    @{ BasePrice = 19.99; Names = @("Stride Yoga Mat", "Forge Resistance Band Set", "Peak Insulated Water Bottle", "Tempo Jump Rope", "Summit Foam Roller", "Trail Running Belt", "Motion Exercise Ball", "Balance Cork Block", "Core Training Gloves", "Sprint Sports Towel", "Rally Pickleball Set", "Quest Hiking Pole", "Flex Stretch Strap", "Pace Running Cap", "Vigor Kettlebell") },
    @{ BasePrice = 29.99; Names = @("Voyager Carry-On Organizer", "Nomad Travel Pillow", "Trek Packing Cube Set", "Roam Passport Wallet", "Coast Luggage Scale", "Vista Daypack", "Drift Toiletry Kit", "Trail Cable Pouch", "Skyline Neck Pillow", "Compass Water Resistant Bag", "Waypoint Travel Adapter", "Harbor RFID Wallet", "Aurora Eye Mask", "Atlas Foldable Tote", "Journey Document Holder") },
    @{ BasePrice = 15.99; Names = @("Brew Pour Over Set", "Savor Coffee Canister", "Garden Herb Scissors", "Pantry Spice Rack", "Copper Measuring Spoon Set", "Stoneware Bowl Set", "Citrus Juice Press", "Oak Rolling Pin", "Flame Oven Mitt Set", "Whisk Silicone Spatula Set", "Harvest Salad Spinner", "Marble Coaster Set", "Baker Cooling Rack", "Sage Tea Infuser", "Crisp Food Storage Set") },
    @{ BasePrice = 34.99; Names = @("Frame City Bicycle Light", "Shield Bike Helmet", "Field Camping Lantern", "River Dry Bag", "Ridge Picnic Blanket", "Campfire Folding Chair", "Coastal Beach Umbrella", "Alpine Thermal Flask", "Summit Trekking Backpack", "Grove Hammock", "Trail First Aid Kit", "Tide Waterproof Phone Case", "Canyon Folding Table", "Glacier Cooler Bag", "Forest Binoculars") },
    @{ BasePrice = 18.99; Names = @("Bloom Skincare Set", "Velvet Makeup Bag", "Pure Bamboo Hairbrush", "Silk Sleep Mask", "Cedar Beard Grooming Kit", "Aura Essential Oil Diffuser", "Cloud Bath Robe", "Mineral Facial Roller", "Dawn Manicure Set", "Petal Hair Clip Set", "Amber Body Lotion", "Satin Cosmetic Mirror", "Fresh Travel Grooming Kit", "Ivy Nail Care Set", "Rose Quartz Gua Sha") },
    @{ BasePrice = 9.99; Names = @("Paws Treat Jar", "Whisker Cat Toy Set", "Bark Travel Bowl", "Pawprint Pet Blanket", "Feline Scratching Pad", "Trail Dog Leash", "Cozy Pet Bed", "Aqua Fish Feeder", "Feather Cat Wand", "Pup Training Clicker", "Nest Bird Feeder", "Paws Grooming Brush", "Fetch Tennis Ball Set", "Tail Waste Bag Holder", "Pet ID Tag Set") },
    @{ BasePrice = 21.99; Names = @("Little Explorer Puzzle", "Rocket Building Blocks", "Rainbow Art Set", "Junior Science Kit", "Storytime Book Light", "Galaxy Craft Box", "Woodland Memory Game", "Ocean Sticker Set", "Castle Play Tent", "Dino Excavation Kit", "Safari Water Bottle", "Robot Coding Cards", "Cloud Night Light", "Map Floor Puzzle", "Space Sketchbook") }
)

$categoryLabels = @(
    "Computer Accessories", "Office Equipment", "Home and Living", "Fitness", "Travel",
    "Kitchen", "Outdoors", "Personal Care", "Pet Supplies", "Kids and Learning"
)
$brandLabels = @(
    "KeyForge", "PaperCraft", "HearthHome", "PeakMotion", "TrailPack",
    "SavorWare", "SummitGear", "AuraCare", "PawFoundry", "BrightMinds"
)
$products = [System.Collections.Generic.List[object]]::new()
$productIndex = 0
for ($groupIndex = 0; $groupIndex -lt $catalogGroups.Count; $groupIndex++) {
    $group = $catalogGroups[$groupIndex]
    foreach ($name in $group.Names) {
        $productIndex++
        $productId = 100 + $productIndex
        $products.Add([pscustomobject]@{
                ProductId = $productId
                ProductName = $name
                Brand = $brandLabels[$groupIndex]
                Model = "SV-{0:D3}-2026" -f $productId
                Category = $categoryLabels[$groupIndex]
                Description = "$name is a catalog item used for checkout, inventory reservation, and order-management workflows."
                ImageKey = "products/$productId.png"
                ImageUrl = "http://localhost:9000/shopverse-product-images/products/$productId.png"
                UnitPrice = [decimal]($group.BasePrice + (($productIndex % 9) * 7.5))
                AvailableQuantity = 40 + (($productIndex * 7) % 61)
            })
    }
}
$products = @($products | Select-Object -First $ProductCount)

function New-CatalogProduct {
    param(
        [long]$ProductId,
        [string]$ProductName,
        [string]$Brand,
        [string]$Model,
        [string]$Category,
        [string]$Description,
        [decimal]$UnitPrice,
        [int]$AvailableQuantity
    )

    [pscustomobject]@{
        ProductId = $ProductId
        ProductName = $ProductName
        Brand = $Brand
        Model = $Model
        Category = $Category
        Description = $Description
        ImageKey = "products/$ProductId.png"
        ImageUrl = "http://localhost:9000/shopverse-product-images/products/$ProductId.png"
        UnitPrice = $UnitPrice
        AvailableQuantity = $AvailableQuantity
    }
}

$baselineProducts = @(
    New-CatalogProduct 101 "Compact Wireless Keyboard K380" "NorthKey" "NK-K380-WL" "Computer Accessories" "A compact wireless keyboard for everyday desk setups, tablets, and travel workspaces." 2799.00 34
    New-CatalogProduct 102 "USB-C 8-in-1 Travel Dock" "Portsmith" "PS-D8C-GRY" "Computer Accessories" "A portable USB-C dock with HDMI, USB-A, Ethernet, card reader, and pass-through charging support." 5499.00 18
    New-CatalogProduct 103 "Hybrid Active Noise Cancelling Headphones" "Auralane" "AL-HYB700-BLK" "Audio" "Over-ear headphones with active noise cancellation, transparency mode, and long battery life for focused work." 9499.00 14
    New-CatalogProduct 104 "27-inch 4K IPS Monitor" "Viewcrest" "VC-IPS4K-27" "Monitors" "A 27-inch 4K IPS monitor with slim bezels, wide viewing angles, and USB-C friendly workstation support." 18999.00 9
    New-CatalogProduct 105 "Ergonomic Silent Wireless Mouse" "ErgoNest" "EN-MX2-SIL" "Computer Accessories" "A silent ergonomic wireless mouse designed for long work sessions and precise everyday navigation." 1799.00 46
    New-CatalogProduct 106 "Hot-Swappable Mechanical Keyboard" "NorthKey" "NK-MK84-HS" "Computer Accessories" "A hot-swappable mechanical keyboard with compact layout, tactile switches, and customizable keycaps." 6999.00 21
    New-CatalogProduct 107 "1080p Autofocus Webcam" "Frameo" "FR-CAM1080-AF" "Computer Accessories" "A 1080p webcam with autofocus and low-light correction for meetings, learning, and livestreaming." 3299.00 27
    New-CatalogProduct 108 "Adjustable Aluminium Laptop Stand" "Deskwise" "DW-LIFT-A2" "Workspace" "An aluminium laptop stand that improves screen height, airflow, and desk ergonomics." 2199.00 32
    New-CatalogProduct 109 "Portable NVMe SSD 1TB" "Vaulton" "VT-NVME-1TB" "Storage" "A rugged portable NVMe SSD for fast backups, media projects, and secure file transfer." 8299.00 16
    New-CatalogProduct 110 "Ergonomic Mesh Office Chair" "PostureWorks" "PW-MESH-PRO" "Workspace" "A breathable mesh office chair with lumbar support, adjustable arms, and tilt control." 21999.00 7
    New-CatalogProduct 111 "GaN USB-C Charging Station 100W" "VoltEdge" "VE-GAN100-4P" "Power and Charging" "A 100W GaN charging station for laptops, phones, tablets, earbuds, and desk accessories." 3999.00 24
    New-CatalogProduct 112 "Dimmable LED Desk Lamp" "LumaNest" "LN-DESK-DIM" "Workspace" "A dimmable LED desk lamp with warm and cool modes for reading, calls, and late-night work." 2499.00 28
    New-CatalogProduct 113 "Portable Bluetooth Speaker" "Auralane" "AL-BT360-MINI" "Audio" "A compact Bluetooth speaker with balanced sound, splash resistance, and all-day portability." 3199.00 22
    New-CatalogProduct 114 "Weather-Resistant Laptop Backpack 25L" "CarryGrid" "CG-COMMUTE-25" "Bags and Travel" "A 25L laptop backpack with weather-resistant fabric, padded device storage, and organized compartments." 3999.00 19
    New-CatalogProduct 115 "Wireless Presentation Remote" "MeetMate" "MM-CLICK-RF" "Computer Accessories" "A wireless presentation remote with slide controls, pointer support, and plug-and-play receiver." 1999.00 31
    New-CatalogProduct 116 "Single Monitor Arm With Gas Spring" "Deskwise" "DW-ARM-GS1" "Workspace" "A gas-spring monitor arm for cleaner desks, flexible screen positioning, and improved posture." 4599.00 12
    New-CatalogProduct 117 "Bluetooth Mechanical Number Pad" "NorthKey" "NK-NPAD-BT" "Computer Accessories" "A Bluetooth mechanical number pad for finance workflows, spreadsheets, and compact keyboards." 2699.00 26
    New-CatalogProduct 118 "Adjustable 1080p Video Ring Light" "Frameo" "FR-RING-1080" "Lighting" "An adjustable ring light for video calls, product photos, and content recording." 1899.00 33
    New-CatalogProduct 119 "USB-C Noise Isolating Earphones" "Auralane" "AL-CBUDS-C" "Audio" "USB-C wired earphones with passive noise isolation, inline controls, and clear voice pickup." 1599.00 39
    New-CatalogProduct 120 "Compact Thermal Label Printer" "Labelry" "LB-PRINT-4X6" "Office Equipment" "A compact thermal label printer for shipping labels, inventory tags, and small business dispatch workflows." 6499.00 15
)

$products = @($baselineProducts | Select-Object -First $ProductCount)

Write-Host "Logging in as '$AdminUsername' through $GatewayUrl..."
$adminToken = Get-AccessToken -Username $AdminUsername -Password $AdminPassword
$adminHeaders = @{ Authorization = "Bearer $adminToken" }

$userResults = [System.Collections.Generic.List[object]]::new()
foreach ($customerIndex in 0..($customers.Count - 1)) {
    $customer = $customers[$customerIndex]
    $payload = @{
        username = $customer.Username
        email = "$($customer.Username)@shopverse.demo"
        password = $CustomerPassword
        firstName = $customer.FirstName
        lastName = $customer.LastName
        phoneNumber = "+1555000{0:D4}" -f ($customerIndex + 1)
        roles = @("ROLE_CUSTOMER")
    }

    try {
        $response = Invoke-ShopverseJson -Method Post -Uri "$GatewayUrl/api/v1/users" -Headers $adminHeaders -Body $payload -TimeoutSeconds $RequestTimeoutSeconds
        $userResults.Add([pscustomobject]@{ Username = $customer.Username; Status = "created"; Id = $response.data.id })
    } catch {
        if ((Get-HttpStatusCode $_) -eq 409) {
            $userResults.Add([pscustomobject]@{ Username = $customer.Username; Status = "existing"; Id = $null })
            continue
        }
        throw "Unable to create customer '$($customer.Username)': $($_.Exception.Message)"
    }
}

$productResults = [System.Collections.Generic.List[object]]::new()
foreach ($product in $products) {
    $payload = @{
        productId = $product.ProductId
        productName = $product.ProductName
        brand = $product.Brand
        model = $product.Model
        category = $product.Category
        description = $product.Description
        imageUrl = $product.ImageUrl
        imageKey = $product.ImageKey
        unitPrice = $product.UnitPrice
        availableQuantity = $product.AvailableQuantity
    }
    $response = Invoke-ShopverseJson -Method Put -Uri "$GatewayUrl/api/v1/inventory/admin/items" -Headers $adminHeaders -Body $payload -TimeoutSeconds $RequestTimeoutSeconds
    $productResults.Add([pscustomobject]@{ ProductId = $product.ProductId; ProductName = $product.ProductName; Status = "upserted"; AvailableQuantity = $response.availableQuantity })
}

Invoke-ShopverseJson `
    -Method Post `
    -Uri "$GatewayUrl/api/v1/orders/admin/catalog-cache/evict" `
    -Headers $adminHeaders `
    -Body $null `
    -TimeoutSeconds $RequestTimeoutSeconds | Out-Null

Write-Host "Created or confirmed $($userResults.Count) customers and upserted $($productResults.Count) products. Starting $OrderCount checkout requests in batches of $BatchSize..."

$checkoutWorker = {
    param($WorkerGatewayUrl, $Username, $Password, $ProductId, $OrderIndex, $TimeoutSeconds)

    $idempotencyKey = "api-seed-checkout-{0:D4}" -f $OrderIndex
    $correlationId = "api-seed-correlation-{0:D4}" -f $OrderIndex
        $body = @{
            items = @(@{ productId = $ProductId; quantity = 1 })
            shippingAddress = @{
                recipientName = $Username
                phoneNumber = "+1555010{0:D4}" -f $OrderIndex
                line1 = "{0} Market Street" -f (100 + $OrderIndex)
                line2 = "Apartment {0}" -f (($OrderIndex % 20) + 1)
                city = "Bengaluru"
                state = "Karnataka"
                postalCode = "560001"
                country = "IN"
            }
        } | ConvertTo-Json -Depth 6 -Compress

    for ($attempt = 1; $attempt -le 4; $attempt++) {
        try {
            $login = Invoke-RestMethod -Method Post -Uri "$WorkerGatewayUrl/auth/login" -ContentType "application/json" -Body (@{ username = $Username; password = $Password } | ConvertTo-Json -Compress) -TimeoutSec $TimeoutSeconds -ErrorAction Stop
            if ([string]::IsNullOrWhiteSpace($login.token)) {
                throw "Login returned no token"
            }
            $headers = @{
                Authorization = "Bearer $($login.token)"
                "Idempotency-Key" = $idempotencyKey
                "X-Correlation-Id" = $correlationId
            }
            $order = Invoke-RestMethod -Method Post -Uri "$WorkerGatewayUrl/api/v1/orders/checkout" -Headers $headers -ContentType "application/json" -Body $body -TimeoutSec $TimeoutSeconds -ErrorAction Stop
            return [pscustomobject]@{
                Success = $true
                OrderIndex = $OrderIndex
                Username = $Username
                ProductId = $ProductId
                OrderId = $order.id
                OrderNumber = $order.orderNumber
                CorrelationId = $correlationId
                IdempotencyKey = $idempotencyKey
                Error = $null
            }
        } catch {
            $statusCode = if ($null -eq $_.Exception.Response) { 0 } else { [int]$_.Exception.Response.StatusCode }
            if ($attempt -eq 4 -or $statusCode -notin @(409, 429, 502, 503, 504)) {
                return [pscustomobject]@{
                    Success = $false
                    OrderIndex = $OrderIndex
                    Username = $Username
                    ProductId = $ProductId
                    OrderId = $null
                    OrderNumber = $null
                    CorrelationId = $correlationId
                    IdempotencyKey = $idempotencyKey
                    Error = "HTTP ${statusCode}: $($_.Exception.Message)"
                }
            }
            Start-Sleep -Milliseconds (350 * $attempt)
        }
    }
}

$checkoutPlan = @(for ($orderIndex = 1; $orderIndex -le $OrderCount; $orderIndex++) {
    [pscustomobject]@{
        OrderIndex = $orderIndex
        Customer = $customers[($orderIndex - 1) % $customers.Count]
        Product = $products[(($orderIndex - 1) * 13) % $products.Count]
    }
})

$orderResults = [System.Collections.Generic.List[object]]::new()
for ($offset = 0; $offset -lt $checkoutPlan.Count; $offset += $BatchSize) {
    $batch = @($checkoutPlan | Select-Object -Skip $offset -First $BatchSize)
    $jobs = foreach ($entry in $batch) {
        Start-Job -ScriptBlock $checkoutWorker -ArgumentList @(
            $GatewayUrl,
            $entry.Customer.Username,
            $CustomerPassword,
            $entry.Product.ProductId,
            $entry.OrderIndex,
            $RequestTimeoutSeconds
        )
    }

    Wait-Job -Job $jobs -Timeout $BatchTimeoutSeconds | Out-Null
    $timedOut = @($jobs | Where-Object State -eq "Running")
    if ($timedOut) {
        $timedOut | Stop-Job
    }
    for ($jobIndex = 0; $jobIndex -lt $jobs.Count; $jobIndex++) {
        $job = $jobs[$jobIndex]
        $result = Receive-Job -Job $job -ErrorAction SilentlyContinue
        if ($null -eq $result) {
            $entry = $batch[$jobIndex]
            $result = [pscustomobject]@{
                Success = $false
                OrderIndex = $entry.OrderIndex
                Username = $entry.Customer.Username
                ProductId = $entry.Product.ProductId
                OrderId = $null
                OrderNumber = $null
                CorrelationId = "api-seed-correlation-{0:D4}" -f $entry.OrderIndex
                IdempotencyKey = "api-seed-checkout-{0:D4}" -f $entry.OrderIndex
                Error = "Checkout batch exceeded the ${BatchTimeoutSeconds}s timeout"
            }
        }
        $orderResults.Add($result)
        Remove-Job -Job $job -Force
    }

    $completedCount = [Math]::Min($offset + $batch.Count, $checkoutPlan.Count)
    Write-Host "Checkout progress: $completedCount / $($checkoutPlan.Count)"
}

$manifestDirectory = Split-Path -Parent $ManifestPath
if (-not [string]::IsNullOrWhiteSpace($manifestDirectory)) {
    New-Item -ItemType Directory -Force -Path $manifestDirectory | Out-Null
}
$manifest = [pscustomobject]@{
    generatedAtUtc = [DateTime]::UtcNow.ToString("o")
    gatewayUrl = $GatewayUrl
    requested = @{ customers = $CustomerCount; products = $ProductCount; orders = $OrderCount }
    summary = @{
        customersCreated = @($userResults | Where-Object Status -eq "created").Count
        customersExisting = @($userResults | Where-Object Status -eq "existing").Count
        productsUpserted = $productResults.Count
        checkoutSucceeded = @($orderResults | Where-Object Success).Count
        checkoutFailed = @($orderResults | Where-Object { -not $_.Success }).Count
    }
    customers = $userResults
    products = $productResults
    orders = $orderResults
}
$manifest | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $ManifestPath -Encoding utf8
Update-GeneratedCredentials -Customers $customers

$failedOrders = @($orderResults | Where-Object { -not $_.Success })
$manifest.summary | Format-List
Write-Host "Credentials: $CredentialsPath"
Write-Host "Manifest: $ManifestPath"

if ($failedOrders.Count -gt 0) {
    $failedOrders | Select-Object OrderIndex, Username, ProductId, Error | Format-Table -AutoSize
    throw "$($failedOrders.Count) checkout requests failed. Re-run the script with the same defaults; successful orders reuse their idempotency keys."
}
