[CmdletBinding()]
param(
    [string]$GatewayUrl = "http://localhost:8080",
    [string]$AdminUsername = "admin",
    [string]$AdminPassword = $env:SHOPVERSE_ADMIN_PASSWORD,
    [ValidateRange(1, 20)]
    [int]$CustomerCount = 20,
    [ValidateRange(1, 20)]
    [int]$ProductCount = 20,
    [ValidateRange(1, 500)]
    [int]$OrderCount = 120,
    [ValidateRange(1, 8)]
    [int]$BatchSize = 4,
    [ValidateRange(5, 60)]
    [int]$RequestTimeoutSeconds = 20,
    [ValidateRange(30, 300)]
    [int]$BatchTimeoutSeconds = 120,
    [string]$CustomerPassword = "Shopverse!2026",
    [string]$CredentialsPath = "",
    [string]$ManifestPath = ""
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$repositoryRoot = Split-Path -Parent $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($CredentialsPath)) {
    $CredentialsPath = Join-Path $repositoryRoot "demo-credentials.local.md"
}
if ([string]::IsNullOrWhiteSpace($ManifestPath)) {
    $ManifestPath = Join-Path $repositoryRoot ".tmp/shopverse-api-seed-manifest.json"
}

function Get-HttpStatusCode {
    param([System.Management.Automation.ErrorRecord]$ErrorRecord)

    if ($null -eq $ErrorRecord.Exception.Response) {
        return 0
    }

    return [int]$ErrorRecord.Exception.Response.StatusCode
}

function Invoke-ShopverseJson {
    param(
        [ValidateSet("Get", "Post", "Put")]
        [string]$Method,
        [string]$Uri,
        [hashtable]$Headers,
        [object]$Body,
        [int]$TimeoutSeconds,
        [int[]]$RetryStatusCodes = @(429, 502, 503, 504)
    )

    $jsonBody = if ($null -eq $Body) { $null } else { $Body | ConvertTo-Json -Depth 8 -Compress }

    for ($attempt = 1; $attempt -le 4; $attempt++) {
        try {
            $parameters = @{
                Method = $Method
                Uri = $Uri
                Headers = $Headers
                TimeoutSec = $TimeoutSeconds
                ErrorAction = "Stop"
            }
            if ($null -ne $jsonBody) {
                $parameters.ContentType = "application/json"
                $parameters.Body = $jsonBody
            }
            return Invoke-RestMethod @parameters
        } catch {
            $statusCode = Get-HttpStatusCode $_
            if ($attempt -eq 4 -or $statusCode -notin $RetryStatusCodes) {
                throw
            }
            Start-Sleep -Milliseconds (250 * $attempt)
        }
    }
}

function Get-AccessToken {
    param(
        [string]$Username,
        [string]$Password
    )

    $login = Invoke-ShopverseJson `
        -Method Post `
        -Uri "$GatewayUrl/auth/login" `
        -Headers @{} `
        -Body @{ username = $Username; password = $Password } `
        -TimeoutSeconds $RequestTimeoutSeconds

    if ([string]::IsNullOrWhiteSpace($login.token)) {
        throw "Login for '$Username' did not return an access token."
    }

    return $login.token
}

function Update-GeneratedCredentials {
    param(
        [object[]]$Customers
    )

    $directory = Split-Path -Parent $CredentialsPath
    if (-not [string]::IsNullOrWhiteSpace($directory)) {
        New-Item -ItemType Directory -Force -Path $directory | Out-Null
    }

    $startMarker = "<!-- SHOPVERSE-API-SEED-START -->"
    $endMarker = "<!-- SHOPVERSE-API-SEED-END -->"
    $rows = $Customers | ForEach-Object {
        "| $($_.Username) | $($_.FirstName) $($_.LastName) | $CustomerPassword | ROLE_CUSTOMER |"
    }
    $section = @(
        $startMarker,
        "",
        "## Generated API Seed Accounts",
        "",
        "Generated by scripts/Seed-ShopverseData.ps1 for local POC use only.",
        "",
        "| Username | Name | Password | Role |",
        "| --- | --- | --- | --- |",
        $rows,
        "",
        "Administrator used by this run: `$AdminUsername`.",
        $endMarker
    ) -join [Environment]::NewLine

    $current = if (Test-Path -LiteralPath $CredentialsPath) {
        Get-Content -LiteralPath $CredentialsPath -Raw
    } else {
        "# Shopverse Local Demo Credentials$([Environment]::NewLine)$([Environment]::NewLine)Keep this ignored file on your local machine only.$([Environment]::NewLine)"
    }

    $pattern = "(?s)" + [regex]::Escape($startMarker) + ".*?" + [regex]::Escape($endMarker)
    $updated = if ($current -match $pattern) {
        [regex]::Replace($current, $pattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($match) $section })
    } else {
        $current.TrimEnd() + [Environment]::NewLine + [Environment]::NewLine + $section + [Environment]::NewLine
    }

    Set-Content -LiteralPath $CredentialsPath -Value $updated -Encoding utf8
}

if ([string]::IsNullOrWhiteSpace($AdminPassword)) {
    $securePassword = Read-Host "Enter the password for $AdminUsername" -AsSecureString
    $pointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($securePassword)
    try {
        $AdminPassword = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($pointer)
    } finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($pointer)
    }
}

$customers = @(
    [pscustomobject]@{ Username = "ana.smith"; FirstName = "Ana"; LastName = "Smith" },
    [pscustomobject]@{ Username = "rose.johnson"; FirstName = "Rose"; LastName = "Johnson" },
    [pscustomobject]@{ Username = "liam.wilson"; FirstName = "Liam"; LastName = "Wilson" },
    [pscustomobject]@{ Username = "emma.brown"; FirstName = "Emma"; LastName = "Brown" },
    [pscustomobject]@{ Username = "noah.davis"; FirstName = "Noah"; LastName = "Davis" },
    [pscustomobject]@{ Username = "olivia.miller"; FirstName = "Olivia"; LastName = "Miller" },
    [pscustomobject]@{ Username = "ethan.moore"; FirstName = "Ethan"; LastName = "Moore" },
    [pscustomobject]@{ Username = "mia.taylor"; FirstName = "Mia"; LastName = "Taylor" },
    [pscustomobject]@{ Username = "james.anderson"; FirstName = "James"; LastName = "Anderson" },
    [pscustomobject]@{ Username = "sophia.thomas"; FirstName = "Sophia"; LastName = "Thomas" },
    [pscustomobject]@{ Username = "benjamin.jackson"; FirstName = "Benjamin"; LastName = "Jackson" },
    [pscustomobject]@{ Username = "isabella.white"; FirstName = "Isabella"; LastName = "White" },
    [pscustomobject]@{ Username = "daniel.harris"; FirstName = "Daniel"; LastName = "Harris" },
    [pscustomobject]@{ Username = "ava.martin"; FirstName = "Ava"; LastName = "Martin" },
    [pscustomobject]@{ Username = "henry.thompson"; FirstName = "Henry"; LastName = "Thompson" },
    [pscustomobject]@{ Username = "charlotte.garcia"; FirstName = "Charlotte"; LastName = "Garcia" },
    [pscustomobject]@{ Username = "lucas.martinez"; FirstName = "Lucas"; LastName = "Martinez" },
    [pscustomobject]@{ Username = "amelia.robinson"; FirstName = "Amelia"; LastName = "Robinson" },
    [pscustomobject]@{ Username = "alexander.clark"; FirstName = "Alexander"; LastName = "Clark" },
    [pscustomobject]@{ Username = "harper.lewis"; FirstName = "Harper"; LastName = "Lewis" }
) | Select-Object -First $CustomerCount

$catalogGroups = @(
    @{ BasePrice = 49.99; Names = @("Nova Wireless Earbuds", "Orbit Bluetooth Speaker", "Pulse Fitness Tracker", "Lumen Desk Lamp", "Vertex USB-C Hub", "Echo Noise Cancelling Headphones", "Aero Portable Charger", "Pixel Web Camera", "Sonic Mini Soundbar", "Volt Smart Plug", "Atlas Tablet Stand", "Wave Mechanical Keyboard", "Prism Wireless Mouse", "Halo LED Monitor Light", "Core Laptop Sleeve") },
    @{ BasePrice = 12.99; Names = @("Canvas Notebook Set", "Graphite Gel Pen Pack", "Cedar Desk Organizer", "Metro Weekly Planner", "Studio Sticky Notes", "Archive File Folder Set", "Focus Timer", "Summit Document Tray", "Craft Paper Cutter", "Signal Desk Clock", "Nordic Pen Holder", "Drafting Ruler Set", "Slate Mouse Pad", "Vision Whiteboard Kit", "Ledger Expense Journal") },
    @{ BasePrice = 24.99; Names = @("Harbor Throw Pillow", "Willow Storage Basket", "Mason Glass Food Container", "Terrace Plant Pot", "Cove Cotton Towel Set", "Ember Scented Candle", "Meadow Table Runner", "Sierra Ceramic Mug Set", "Solstice Wall Clock", "Hearth Bamboo Cutting Board", "Loft Laundry Basket", "Orchid Bedside Lamp", "Luna Picture Frame", "Birch Serving Tray", "Fern Shower Caddy") },
    @{ BasePrice = 19.99; Names = @("Stride Yoga Mat", "Forge Resistance Band Set", "Peak Insulated Water Bottle", "Tempo Jump Rope", "Summit Foam Roller", "Trail Running Belt", "Motion Exercise Ball", "Balance Cork Block", "Core Training Gloves", "Sprint Sports Towel", "Rally Pickleball Set", "Quest Hiking Pole", "Flex Stretch Strap", "Pace Running Cap", "Vigor Kettlebell") },
    @{ BasePrice = 29.99; Names = @("Voyager Carry-On Organizer", "Nomad Travel Pillow", "Trek Packing Cube Set", "Roam Passport Wallet", "Coast Luggage Scale", "Vista Daypack", "Drift Toiletry Kit", "Trail Cable Pouch", "Skyline Neck Pillow", "Compass Water Resistant Bag", "Waypoint Travel Adapter", "Harbor RFID Wallet", "Aurora Eye Mask", "Atlas Foldable Tote", "Journey Document Holder") },
    @{ BasePrice = 15.99; Names = @("Brew Pour Over Set", "Savor Coffee Canister", "Garden Herb Scissors", "Pantry Spice Rack", "Copper Measuring Spoon Set", "Stoneware Bowl Set", "Citrus Juice Press", "Oak Rolling Pin", "Flame Oven Mitt Set", "Whisk Silicone Spatula Set", "Harvest Salad Spinner", "Marble Coaster Set", "Baker Cooling Rack", "Sage Tea Infuser", "Crisp Food Storage Set") },
    @{ BasePrice = 34.99; Names = @("Frame City Bicycle Light", "Shield Bike Helmet", "Field Camping Lantern", "River Dry Bag", "Ridge Picnic Blanket", "Campfire Folding Chair", "Coastal Beach Umbrella", "Alpine Thermal Flask", "Summit Trekking Backpack", "Grove Hammock", "Trail First Aid Kit", "Tide Waterproof Phone Case", "Canyon Folding Table", "Glacier Cooler Bag", "Forest Binoculars") },
    @{ BasePrice = 18.99; Names = @("Bloom Skincare Set", "Velvet Makeup Bag", "Pure Bamboo Hairbrush", "Silk Sleep Mask", "Cedar Beard Grooming Kit", "Aura Essential Oil Diffuser", "Cloud Bath Robe", "Mineral Facial Roller", "Dawn Manicure Set", "Petal Hair Clip Set", "Amber Body Lotion", "Satin Cosmetic Mirror", "Fresh Travel Grooming Kit", "Ivy Nail Care Set", "Rose Quartz Gua Sha") },
    @{ BasePrice = 9.99; Names = @("Paws Treat Jar", "Whisker Cat Toy Set", "Bark Travel Bowl", "Pawprint Pet Blanket", "Feline Scratching Pad", "Trail Dog Leash", "Cozy Pet Bed", "Aqua Fish Feeder", "Feather Cat Wand", "Pup Training Clicker", "Nest Bird Feeder", "Paws Grooming Brush", "Fetch Tennis Ball Set", "Tail Waste Bag Holder", "Pet ID Tag Set") },
    @{ BasePrice = 21.99; Names = @("Little Explorer Puzzle", "Rocket Building Blocks", "Rainbow Art Set", "Junior Science Kit", "Storytime Book Light", "Galaxy Craft Box", "Woodland Memory Game", "Ocean Sticker Set", "Castle Play Tent", "Dino Excavation Kit", "Safari Water Bottle", "Robot Coding Cards", "Cloud Night Light", "Map Floor Puzzle", "Space Sketchbook") }
)

$categoryLabels = @(
    "Computer Accessories", "Office Equipment", "Home and Living", "Fitness", "Travel",
    "Kitchen", "Outdoors", "Personal Care", "Pet Supplies", "Kids and Learning"
)
$brandLabels = @(
    "KeyForge", "PaperCraft", "HearthHome", "PeakMotion", "TrailPack",
    "SavorWare", "SummitGear", "AuraCare", "PawFoundry", "BrightMinds"
)
$products = [System.Collections.Generic.List[object]]::new()
$productIndex = 0
for ($groupIndex = 0; $groupIndex -lt $catalogGroups.Count; $groupIndex++) {
    $group = $catalogGroups[$groupIndex]
    foreach ($name in $group.Names) {
        $productIndex++
        $productId = 100 + $productIndex
        $products.Add([pscustomobject]@{
                ProductId = $productId
                ProductName = $name
                Brand = $brandLabels[$groupIndex]
                Model = "SV-{0:D3}-2026" -f $productId
                Category = $categoryLabels[$groupIndex]
                Description = "$name is a Shopverse demonstration product for catalog, checkout, and inventory reservation flows."
                ImageKey = "products/$productId.png"
                ImageUrl = "http://localhost:9000/shopverse-product-images/products/$productId.png"
                UnitPrice = [decimal]($group.BasePrice + (($productIndex % 9) * 7.5))
                AvailableQuantity = 40 + (($productIndex * 7) % 61)
            })
    }
}
$products = @($products | Select-Object -First $ProductCount)

Write-Host "Logging in as '$AdminUsername' through $GatewayUrl..."
$adminToken = Get-AccessToken -Username $AdminUsername -Password $AdminPassword
$adminHeaders = @{ Authorization = "Bearer $adminToken" }

$userResults = [System.Collections.Generic.List[object]]::new()
foreach ($customerIndex in 0..($customers.Count - 1)) {
    $customer = $customers[$customerIndex]
    $payload = @{
        username = $customer.Username
        email = "$($customer.Username)@shopverse.demo"
        password = $CustomerPassword
        firstName = $customer.FirstName
        lastName = $customer.LastName
        phoneNumber = "+1555000{0:D4}" -f ($customerIndex + 1)
        roles = @("ROLE_CUSTOMER")
    }

    try {
        $response = Invoke-ShopverseJson -Method Post -Uri "$GatewayUrl/api/v1/users" -Headers $adminHeaders -Body $payload -TimeoutSeconds $RequestTimeoutSeconds
        $userResults.Add([pscustomobject]@{ Username = $customer.Username; Status = "created"; Id = $response.data.id })
    } catch {
        if ((Get-HttpStatusCode $_) -eq 409) {
            $userResults.Add([pscustomobject]@{ Username = $customer.Username; Status = "existing"; Id = $null })
            continue
        }
        throw "Unable to create customer '$($customer.Username)': $($_.Exception.Message)"
    }
}

$productResults = [System.Collections.Generic.List[object]]::new()
foreach ($product in $products) {
    $payload = @{
        productId = $product.ProductId
        productName = $product.ProductName
        brand = $product.Brand
        model = $product.Model
        category = $product.Category
        description = $product.Description
        imageUrl = $product.ImageUrl
        imageKey = $product.ImageKey
        unitPrice = $product.UnitPrice
        availableQuantity = $product.AvailableQuantity
    }
    $response = Invoke-ShopverseJson -Method Put -Uri "$GatewayUrl/api/v1/inventory/admin/items" -Headers $adminHeaders -Body $payload -TimeoutSeconds $RequestTimeoutSeconds
    $productResults.Add([pscustomobject]@{ ProductId = $product.ProductId; ProductName = $product.ProductName; Status = "upserted"; AvailableQuantity = $response.availableQuantity })
}

Write-Host "Created or confirmed $($userResults.Count) customers and upserted $($productResults.Count) products. Starting $OrderCount checkout requests in batches of $BatchSize..."

$checkoutWorker = {
    param($WorkerGatewayUrl, $Username, $Password, $ProductId, $OrderIndex, $TimeoutSeconds)

    $idempotencyKey = "api-seed-checkout-{0:D4}" -f $OrderIndex
    $correlationId = "api-seed-correlation-{0:D4}" -f $OrderIndex
    $body = @{ items = @(@{ productId = $ProductId; quantity = 1 }) } | ConvertTo-Json -Depth 6 -Compress

    for ($attempt = 1; $attempt -le 4; $attempt++) {
        try {
            $login = Invoke-RestMethod -Method Post -Uri "$WorkerGatewayUrl/auth/login" -ContentType "application/json" -Body (@{ username = $Username; password = $Password } | ConvertTo-Json -Compress) -TimeoutSec $TimeoutSeconds -ErrorAction Stop
            if ([string]::IsNullOrWhiteSpace($login.token)) {
                throw "Login returned no token"
            }
            $headers = @{
                Authorization = "Bearer $($login.token)"
                "Idempotency-Key" = $idempotencyKey
                "X-Correlation-Id" = $correlationId
            }
            $order = Invoke-RestMethod -Method Post -Uri "$WorkerGatewayUrl/api/v1/orders/checkout" -Headers $headers -ContentType "application/json" -Body $body -TimeoutSec $TimeoutSeconds -ErrorAction Stop
            return [pscustomobject]@{
                Success = $true
                OrderIndex = $OrderIndex
                Username = $Username
                ProductId = $ProductId
                OrderId = $order.id
                OrderNumber = $order.orderNumber
                CorrelationId = $correlationId
                IdempotencyKey = $idempotencyKey
                Error = $null
            }
        } catch {
            $statusCode = if ($null -eq $_.Exception.Response) { 0 } else { [int]$_.Exception.Response.StatusCode }
            if ($attempt -eq 4 -or $statusCode -notin @(409, 429, 502, 503, 504)) {
                return [pscustomobject]@{
                    Success = $false
                    OrderIndex = $OrderIndex
                    Username = $Username
                    ProductId = $ProductId
                    OrderId = $null
                    OrderNumber = $null
                    CorrelationId = $correlationId
                    IdempotencyKey = $idempotencyKey
                    Error = "HTTP ${statusCode}: $($_.Exception.Message)"
                }
            }
            Start-Sleep -Milliseconds (350 * $attempt)
        }
    }
}

$checkoutPlan = @(for ($orderIndex = 1; $orderIndex -le $OrderCount; $orderIndex++) {
    [pscustomobject]@{
        OrderIndex = $orderIndex
        Customer = $customers[($orderIndex - 1) % $customers.Count]
        Product = $products[(($orderIndex - 1) * 13) % $products.Count]
    }
})

$orderResults = [System.Collections.Generic.List[object]]::new()
for ($offset = 0; $offset -lt $checkoutPlan.Count; $offset += $BatchSize) {
    $batch = @($checkoutPlan | Select-Object -Skip $offset -First $BatchSize)
    $jobs = foreach ($entry in $batch) {
        Start-Job -ScriptBlock $checkoutWorker -ArgumentList @(
            $GatewayUrl,
            $entry.Customer.Username,
            $CustomerPassword,
            $entry.Product.ProductId,
            $entry.OrderIndex,
            $RequestTimeoutSeconds
        )
    }

    Wait-Job -Job $jobs -Timeout $BatchTimeoutSeconds | Out-Null
    $timedOut = @($jobs | Where-Object State -eq "Running")
    if ($timedOut) {
        $timedOut | Stop-Job
    }
    for ($jobIndex = 0; $jobIndex -lt $jobs.Count; $jobIndex++) {
        $job = $jobs[$jobIndex]
        $result = Receive-Job -Job $job -ErrorAction SilentlyContinue
        if ($null -eq $result) {
            $entry = $batch[$jobIndex]
            $result = [pscustomobject]@{
                Success = $false
                OrderIndex = $entry.OrderIndex
                Username = $entry.Customer.Username
                ProductId = $entry.Product.ProductId
                OrderId = $null
                OrderNumber = $null
                CorrelationId = "api-seed-correlation-{0:D4}" -f $entry.OrderIndex
                IdempotencyKey = "api-seed-checkout-{0:D4}" -f $entry.OrderIndex
                Error = "Checkout batch exceeded the ${BatchTimeoutSeconds}s timeout"
            }
        }
        $orderResults.Add($result)
        Remove-Job -Job $job -Force
    }

    $completedCount = [Math]::Min($offset + $batch.Count, $checkoutPlan.Count)
    Write-Host "Checkout progress: $completedCount / $($checkoutPlan.Count)"
}

$manifestDirectory = Split-Path -Parent $ManifestPath
if (-not [string]::IsNullOrWhiteSpace($manifestDirectory)) {
    New-Item -ItemType Directory -Force -Path $manifestDirectory | Out-Null
}
$manifest = [pscustomobject]@{
    generatedAtUtc = [DateTime]::UtcNow.ToString("o")
    gatewayUrl = $GatewayUrl
    requested = @{ customers = $CustomerCount; products = $ProductCount; orders = $OrderCount }
    summary = @{
        customersCreated = @($userResults | Where-Object Status -eq "created").Count
        customersExisting = @($userResults | Where-Object Status -eq "existing").Count
        productsUpserted = $productResults.Count
        checkoutSucceeded = @($orderResults | Where-Object Success).Count
        checkoutFailed = @($orderResults | Where-Object { -not $_.Success }).Count
    }
    customers = $userResults
    products = $productResults
    orders = $orderResults
}
$manifest | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $ManifestPath -Encoding utf8
Update-GeneratedCredentials -Customers $customers

$failedOrders = @($orderResults | Where-Object { -not $_.Success })
$manifest.summary | Format-List
Write-Host "Credentials: $CredentialsPath"
Write-Host "Manifest: $ManifestPath"

if ($failedOrders.Count -gt 0) {
    $failedOrders | Select-Object OrderIndex, Username, ProductId, Error | Format-Table -AutoSize
    throw "$($failedOrders.Count) checkout requests failed. Re-run the script with the same defaults; successful orders reuse their idempotency keys."
}
