import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'README',
    'reference/LEARNING-PATH',
    'reference/DOCUMENTATION-STRUCTURE',
    {
      type: 'category',
      label: '1. Engineering Foundations',
      collapsed: false,
      items: [
        'development/ENGINEERING-PRINCIPLES',
        'development/DESIGN-PATTERNS',
        {
          type: 'category',
          label: 'HLD And LLD',
          items: [
            'architecture/HLD-LLD',
            'architecture/hld-lld/HLD-FUNDAMENTALS',
            'architecture/hld-lld/CAPACITY-PERFORMANCE-ESTIMATION',
            'architecture/hld-lld/NON-FUNCTIONAL-REQUIREMENTS',
            'architecture/hld-lld/LLD-EXAMPLES-DIAGRAMS',
            'architecture/hld-lld/DATABASE-LLD-DESIGN-PROCESS',
          ],
        },
        'development/REST-API-GENERIC',
        {
          type: 'category',
          label: 'Data Structures',
          items: [
            'data-structures/DATA-STRUCTURES-FUNDAMENTALS',
            'data-structures/LINEAR-DATA-STRUCTURES',
            'data-structures/NON-LINEAR-DATA-STRUCTURES',
          ],
        },
        'operations/GIT-COMMANDS',
      ],
    },
    {
      type: 'category',
      label: '2. Java Fundamentals',
      items: [
        'java/JAVA-FUNDAMENTALS',
        'java/JAVA-OOP',
        'java/JAVA-COLLECTIONS',
        'java/JAVA-COLLECTION-INTERNALS',
        'java/JAVA-STREAMS',
        'java/JAVA-FUNCTIONAL-INTERFACES',
        'java/JAVA-MULTITHREADING',
        'java/JAVA-COMPLETABLE-FUTURE',
        {
          type: 'category',
          label: 'Java 8 To 21 Features',
          items: [
            'java/features-8-to-21/JAVA-8-TO-21',
            'java/features-8-to-21/JAVA-OPTIONAL',
            'java/features-8-to-21/JAVA-VAR',
            'java/features-8-to-21/JAVA-SWITCH',
            'java/features-8-to-21/JAVA-RECORDS',
            'java/features-8-to-21/JAVA-SEALED-CLASSES',
            'java/features-8-to-21/JAVA-VIRTUAL-THREADS',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '3. Spring Ecosystem',
      items: [
        'spring/SPRING-ECOSYSTEM',
        'spring/SPRING-SPEL',
        {
          type: 'category',
          label: 'Spring Boot Internals',
          items: [
            'development/SPRING-BOOT-INTERNALS',
            'development/spring-boot-internals/STARTUP-AUTOCONFIGURATION',
            'development/spring-boot-internals/DI-BEAN-LIFECYCLE-AOP',
            'development/spring-boot-internals/CONFIGURATION-PROPERTIES',
            'development/spring-boot-internals/WEB-MVC-SERVLET-FILTERS',
            'development/spring-boot-internals/INFRASTRUCTURE-INTERNALS',
            'development/spring-boot-internals/OPERATIONS-INTERNALS',
            'development/spring-boot-internals/PRODUCTION-TUNING',
          ],
        },
        'spring/SPRING-ECOSYSTEM-INTERVIEW',
        {
          type: 'category',
          label: 'Spring REST APIs',
          items: [
            'development/SPRING-REST-APIS',
            'development/spring-rest/REST-BASICS-CRUD',
            'development/spring-rest/REST-MAPPING-VALIDATION-ERRORS',
            'development/spring-rest/REST-FILES-PAGINATION-IDEMPOTENCY',
            'development/spring-rest/REST-CLIENTS-FEIGN',
            'development/spring-rest/REST-TESTING-INTERVIEW',
          ],
        },
        'spring/SPRING-AOP',
        'spring/SPRING-CACHE',
        'spring/SPRING-TRANSACTIONS',
        {
          type: 'category',
          label: 'Spring Data JPA',
          items: [
            'spring/SPRING-DATA-JPA',
            'spring/jpa/JPA-BASICS-ENTITY-MAPPING',
            'spring/jpa/JPA-RELATIONSHIPS-JSON',
            'spring/jpa/JPA-REPOSITORIES-QUERIES',
            'spring/jpa/JPA-FETCHING-PERFORMANCE',
            'spring/jpa/JPA-TRANSACTIONS-LOCKING',
            'spring/jpa/JPA-AUDITING-DELETING-TESTING',
          ],
        },
        'spring/SPRING-VALIDATION',
        'spring/SPRING-OPENFEIGN',
        {
          type: 'category',
          label: 'Spring Kafka',
          items: [
            'spring/SPRING-KAFKA',
            'spring/kafka/SPRING-KAFKA-BASICS',
            'spring/kafka/SPRING-KAFKA-CONSUMERS',
            'spring/kafka/SPRING-KAFKA-CONCURRENCY-CAPACITY',
            'spring/kafka/SPRING-KAFKA-RETRY-DLT-RECOVERY',
            'spring/kafka/SPRING-KAFKA-IDEMPOTENCY-OPERATIONS',
          ],
        },
        'spring/SPRING-RESILIENCE4J',
        {
          type: 'category',
          label: 'Spring Boot Testing',
          items: [
            'spring/SPRING-BOOT-TESTING',
            'spring/testing/JUNIT-TESTING-FUNDAMENTALS',
            'spring/testing/MOCKITO-UNIT-TESTING',
            'spring/testing/SPRING-MVC-REPOSITORY-SECURITY-TESTS',
            'spring/testing/INTEGRATION-TESTCONTAINERS',
            'spring/testing/COVERAGE-TEST-QUALITY',
            'spring/testing/ASYNC-CONTRACT-FLAKY-TESTS',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '4. Data And Persistence',
      items: [
        'data/DATABASE-ENGINEERING',
        {
          type: 'category',
          label: 'Hibernate',
          items: [
            'data/HIBERNATE',
            'data/hibernate/HIBERNATE-BASICS-LIFECYCLE',
            'data/hibernate/HIBERNATE-ANNOTATIONS-MAPPING',
            'data/hibernate/HIBERNATE-AUDITING-VALIDATION',
            'data/hibernate/HIBERNATE-FETCHING-PERFORMANCE',
            'data/hibernate/HIBERNATE-INTERVIEW-SCENARIOS',
          ],
        },
        'data/LIQUIBASE-GENERIC',
        'architecture/CACHING-GENERIC',
      ],
    },
    {
      type: 'category',
      label: '5. Microservices And Distributed Systems',
      items: [
        'architecture/MICROSERVICES-DISTRIBUTED-SYSTEMS',
        {
          type: 'category',
          label: 'Architecture Basics',
          items: [
            'architecture/MICROSERVICES-GENERIC',
            'architecture/DISTRIBUTED-SYSTEMS-GENERIC',
            'development/API-GATEWAY-GENERIC',
            'development/SPRING-CLOUD-GATEWAY-ADVANCED',
            'architecture/SERVICE-DISCOVERY',
            'architecture/LOAD-BALANCING-GENERIC',
            'architecture/CQRS',
          ],
        },
        {
          type: 'category',
          label: 'Consistency And Coordination',
          items: [
            'architecture/DISTRIBUTED-CONSISTENCY-CAP',
            'data/DISTRIBUTED-DATABASES',
            'reliability/DISTRIBUTED-TRANSACTIONS-LOCKS',
            {
              type: 'category',
              label: 'Locking And Work Ownership',
              items: [
                'reliability/locking/LOCKING-AND-WORK-OWNERSHIP',
                'reliability/locking/DATABASE-LOCKING-AND-CLAIMS',
                'reliability/locking/SCHEDULER-LOCKING-SHEDLOCK',
                'reliability/locking/DISTRIBUTED-LOCKS-AND-FENCING',
                'reliability/locking/PARTITION-AND-QUEUE-OWNERSHIP',
              ],
            },
            'reliability/SAGA-GENERIC',
            'reliability/OUTBOX-PATTERN',
            'reliability/INBOX-PATTERN',
          ],
        },
        {
          type: 'category',
          label: 'Reliability Patterns',
          items: [
            'reliability/RESILIENCE4J-GENERIC',
            'reliability/DISTRIBUTED-RATE-LIMITING',
            'reliability/HIGH-AVAILABILITY-SPOF',
            'reliability/DISTRIBUTED-FAILURE-CONSENSUS',
          ],
        },
        {
          type: 'category',
          label: 'Messaging',
          items: [
            'integration/APACHE-KAFKA',
          ],
        },
        'reference/DISTRIBUTED-SYSTEMS-INTERVIEW',
      ],
    },
    {
      type: 'category',
      label: '6. Security',
      items: [
        {
          type: 'category',
          label: 'Security Principles',
          items: [
            'security/principles/SECURITY-PRINCIPLES',
            'security/principles/API-SECURITY-PRINCIPLES',
            'security/principles/MICROSERVICES-SECURITY-PRINCIPLES',
            'security/principles/SERVICE-TO-SERVICE-SECURITY',
            'security/principles/SECRETS-AND-CREDENTIALS',
          ],
        },
        {
          type: 'category',
          label: 'JWT',
          items: [
            'security/jwt/JWT-FUNDAMENTALS',
            'security/jwt/JWKS-ASYMMETRIC-JWT',
            'security/jwt/JWT-CLAIMS-ROLES-SCOPES',
            'security/jwt/JWT-BEST-PRACTICES',
          ],
        },
        {
          type: 'category',
          label: 'OAuth2 And OIDC',
          items: [
            'security/oauth/OAUTH2-FUNDAMENTALS',
            'security/oauth/OAUTH2-GRANT-TYPES',
            'security/oauth/OIDC-FUNDAMENTALS',
            'security/oauth/TOKEN-LIFECYCLE',
          ],
        },
        {
          type: 'category',
          label: 'Spring Security',
          items: [
            'security/SPRING-SECURITY-GENERIC',
            'security/spring-security/AUTHENTICATION-BASICS',
            'security/spring-security/SERVLET-FILTER-CHAIN',
            'security/spring-security/JWT-JWKS-RESOURCE-SERVER',
            'security/spring-security/AUTHORIZATION-METHOD-SECURITY',
            'security/spring-security/OAUTH2-OIDC-FLOWS',
            'security/spring-security/PRODUCTION-PRACTICES',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '7. Logging And Observability',
      items: [
        'observability/LOGGING-GENERIC',
        'observability/MDC-GENERIC',
        'observability/MICROMETER-METRICS',
        'observability/PROMETHEUS',
        'observability/LOKI',
        'observability/PROMTAIL',
        'observability/GRAFANA',
      ],
    },
    {
      type: 'category',
      label: '8. Delivery, Containers And CI/CD',
      items: [
        'operations/DEPLOYMENT-STRATEGIES',
        'operations/DOCKER',
        'operations/SHOPVERSE-DOCKER',
        'operations/CI-CD-AUTOMATION',
        'operations/JENKINS',
        'operations/SHOPVERSE-JENKINS',
        'operations/GITHUB-ACTIONS',
        'operations/DOCUSAURUS',
        'operations/SPRING-BOOT-ADMIN',
        'operations/OPERATIONS-CHEATSHEET',
      ],
    },
    {
      type: 'category',
      label: 'Shopverse Case Study',
      collapsed: false,
      items: [
        'case-study/SHOPVERSE',
        'case-study/COMPLETE-DEMO',
        'architecture/SYSTEM-DESIGN',
        'services/SERVICE-CATALOG',
        'reference/FEATURES-AND-DEMOS',
        'development/API-GUIDE',
        'architecture/DISTRIBUTED-SYSTEMS',
        'reliability/SAGA-OUTBOX',
        'reliability/SHOPVERSE-SAGA-CODE-FLOW',
        'reliability/TRANSACTIONS',
        'reliability/RESILIENCE4J',
        'security/JWT-OAUTH2-SPRING-SECURITY',
        'observability/OBSERVABILITY',
        'observability/SHOPVERSE-OBSERVABILITY-OPERATIONS',
        'observability/MDC-CORRELATION-TRACING',
        'observability/STRUCTURED-LOGGING',
        'development/TESTING',
        'development/DEBUGGING',
        {
          type: 'category',
          label: 'Problems And Solutions',
          items: [
            'reliability/PROBLEMS-AND-SOLUTIONS',
            {
              type: 'category',
              label: 'Runtime Reliability Problems',
              items: [
                'reliability/problems/RUNTIME-RELIABILITY-PROBLEMS',
                'reliability/problems/runtime/INDEX-AND-LOCKING',
                'reliability/problems/runtime/DISTRIBUTED-CHECKOUT',
                'reliability/problems/runtime/QUERYABLE-ORDER-TIMELINE',
                'reliability/problems/runtime/RESOURCE-OWNERSHIP-AUTHORIZATION',
                {
                  type: 'category',
                  label: 'Reservation Expiry And Recovery',
                  items: [
                    'reliability/problems/runtime/MULTI-REPLICA-RESERVATION-EXPIRY',
                    'reliability/problems/runtime/ATOMIC-RESERVATION-CLAIM',
                    'reliability/problems/runtime/TWO-SCHEDULER-RESERVATION-EXAMPLE',
                    'reliability/problems/runtime/LATE-PAYMENT-AFTER-EXPIRY',
                  ],
                },
                'reliability/problems/runtime/IDEMPOTENT-CHECKOUT',
                'reliability/problems/runtime/KAFKA-IDEMPOTENCY',
                'reliability/problems/runtime/PAYMENT-TIMEOUT-RECONCILIATION',
              ],
            },
            'reliability/problems/OUTBOX-RUNTIME-PROBLEMS',
            'reliability/problems/DOCKER-RUNTIME-IMAGE-PROBLEMS',
            'reliability/problems/DEPENDENCY-VERIFICATION-PROBLEMS',
            'reliability/problems/PROBLEMS-SUMMARY-LINKS',
          ],
        },
        'reference/CODE-CROSS-CHECK',
      ],
    },
  ],
};

export default sidebars;
