import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'README',
    'reference/LEARNING-PATH',
    'reference/DOCUMENTATION-STRUCTURE',
    'reference/DOCUMENTATION-MAINTENANCE-MAP',
    {
      type: 'category',
      label: '1. Engineering Foundations',
      collapsed: false,
      items: [
        'development/ENGINEERING-PRINCIPLES',
        {
          type: 'category',
          label: 'Design Patterns',
          items: [
            'development/DESIGN-PATTERNS',
            'development/design-patterns/CREATIONAL-PATTERNS',
            'development/design-patterns/STRUCTURAL-PATTERNS',
            'development/design-patterns/BEHAVIORAL-PATTERNS',
          ],
        },
        {
          type: 'category',
          label: 'HLD And LLD',
          items: [
            'architecture/HLD-LLD',
            {
              type: 'category',
              label: 'HLD',
              items: [
                'architecture/hld-lld/HLD-FUNDAMENTALS',
                'architecture/hld-lld/hld/INTRODUCTION-TO-HLD',
                'architecture/hld-lld/NON-FUNCTIONAL-REQUIREMENTS',
                'architecture/hld-lld/CAPACITY-PERFORMANCE-ESTIMATION',
                'architecture/hld-lld/DATA-PARTITIONING',
                'architecture/hld-lld/hld/AVAILABILITY',
                'architecture/hld-lld/hld/CAP-THEOREM',
                'architecture/hld-lld/hld/CONSISTENCY',
                'architecture/hld-lld/hld/CONTENT-DELIVERY-NETWORK',
              ],
            },
            {
              type: 'category',
              label: 'LLD',
              items: [
                'architecture/hld-lld/LLD-EXAMPLES-DIAGRAMS',
                'architecture/hld-lld/UML-DIAGRAMS',
                'architecture/hld-lld/ERD-DIAGRAMS',
                'architecture/hld-lld/DATABASE-LLD-DESIGN-PROCESS',
              ],
            },
          ],
        },
        'development/REST-API-GENERIC',
        {
          type: 'category',
          label: 'Data Structures',
          items: [
            'data-structures/DATA-STRUCTURES-FUNDAMENTALS',
            'data-structures/LINEAR-DATA-STRUCTURES',
            'data-structures/NON-LINEAR-DATA-STRUCTURES',
          ],
        },
        'operations/GIT-COMMANDS',
      ],
    },
    {
      type: 'category',
      label: '2. Java Fundamentals',
      items: [
        'java/JAVA-FUNDAMENTALS',
        'java/JAVA-8-TO-26',
        'java/JAVA-JVM-MEMORY',
        'java/JAVA-THREADING-MODEL',
        'java/JAVA-OOP',
        'java/JAVA-GENERICS',
        'java/JAVA-ENUMS',
        'java/JAVA-SERIALIZATION',
        'java/JAVA-COLLECTIONS',
        'java/JAVA-COLLECTION-INTERNALS',
        'java/JAVA-STREAMS',
        'java/JAVA-FUNCTIONAL-INTERFACES',
        'java/JAVA-MULTITHREADING',
        'java/JAVA-COMPLETABLE-FUTURE',
        {
          type: 'category',
          label: 'Java 8 To 26 Features',
          items: [
            'java/features-8-to-26/JAVA-8-TO-26',
            'java/features-8-to-26/JAVA-LAMBDAS',
            'java/features-8-to-26/JAVA-OPTIONAL',
            'java/features-8-to-26/JAVA-VAR',
            'java/features-8-to-26/JAVA-SWITCH',
            'java/features-8-to-26/JAVA-RECORDS',
            'java/features-8-to-26/JAVA-SEALED-CLASSES',
            'java/features-8-to-26/JAVA-VIRTUAL-THREADS',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '3. Spring Ecosystem',
      items: [
        'spring/README',
        'spring/SPRING-ECOSYSTEM',
        'spring/SPRING-SPEL',
        {
          type: 'category',
          label: 'Spring Boot Internals',
          items: [
            'development/SPRING-BOOT-INTERNALS',
            'development/spring-boot-internals/STARTUP-AUTOCONFIGURATION',
            'development/spring-boot-internals/DI-BEAN-LIFECYCLE-AOP',
            'development/spring-boot-internals/CONFIGURATION-PROPERTIES',
            'development/spring-boot-internals/WEB-MVC-SERVLET-FILTERS',
            'development/spring-boot-internals/INFRASTRUCTURE-INTERNALS',
            'development/spring-boot-internals/OPERATIONS-INTERNALS',
            'development/spring-boot-internals/PRODUCTION-TUNING',
          ],
        },
        'spring/SPRING-ECOSYSTEM-INTERVIEW',
        {
          type: 'category',
          label: 'Spring REST APIs',
          items: [
            'development/SPRING-REST-APIS',
            'development/spring-rest/REST-BASICS-CRUD',
            'development/spring-rest/REST-MAPPING-VALIDATION-ERRORS',
            'development/spring-rest/REST-FILES-PAGINATION-IDEMPOTENCY',
            'development/spring-rest/REST-CLIENTS-FEIGN',
            'development/spring-rest/REST-TESTING-INTERVIEW',
          ],
        },
        'spring/SPRING-AOP',
        'spring/SPRING-CACHE',
        'spring/SPRING-TRANSACTIONS',
        {
          type: 'category',
          label: 'Spring Data JPA',
          items: [
            'spring/SPRING-DATA-JPA',
            'spring/jpa/JPA-BASICS-ENTITY-MAPPING',
            'spring/jpa/JPA-RELATIONSHIPS-JSON',
            'spring/jpa/JPA-REPOSITORIES-QUERIES',
            'spring/jpa/JPA-FETCHING-PERFORMANCE',
            'spring/jpa/JPA-TRANSACTIONS-LOCKING',
            'spring/jpa/JPA-AUDITING-DELETING-TESTING',
          ],
        },
        'spring/SPRING-VALIDATION',
        'spring/SPRING-OPENFEIGN',
        {
          type: 'category',
          label: 'Spring Kafka',
          items: [
            'spring/SPRING-KAFKA',
            'spring/kafka/SPRING-KAFKA-BASICS',
            'spring/kafka/SPRING-KAFKA-CONSUMERS',
            'spring/kafka/SPRING-KAFKA-CONCURRENCY-CAPACITY',
            'spring/kafka/SPRING-KAFKA-RETRY-DLT-RECOVERY',
            'spring/kafka/SPRING-KAFKA-IDEMPOTENCY-OPERATIONS',
          ],
        },
        'spring/SPRING-RESILIENCE4J',
        {
          type: 'category',
          label: 'Spring Boot Testing',
          items: [
            'spring/SPRING-BOOT-TESTING',
            'spring/testing/JUNIT-TESTING-FUNDAMENTALS',
            'spring/testing/MOCKITO-UNIT-TESTING',
            'spring/testing/SPRING-MVC-REPOSITORY-SECURITY-TESTS',
            'spring/testing/INTEGRATION-TESTCONTAINERS',
            'spring/testing/COVERAGE-TEST-QUALITY',
            'spring/testing/ASYNC-CONTRACT-FLAKY-TESTS',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '4. Data And Persistence',
      items: [
        'data/DATABASE-ENGINEERING',
        {
          type: 'category',
          label: 'Hibernate',
          items: [
            'data/HIBERNATE',
            'data/hibernate/HIBERNATE-BASICS-LIFECYCLE',
            'data/hibernate/HIBERNATE-ANNOTATIONS-MAPPING',
            'data/hibernate/HIBERNATE-AUDITING-VALIDATION',
            'data/hibernate/HIBERNATE-FETCHING-PERFORMANCE',
            'data/hibernate/HIBERNATE-INTERVIEW-SCENARIOS',
          ],
        },
        'data/LIQUIBASE-GENERIC',
        'architecture/CACHING-GENERIC',
      ],
    },
    {
      type: 'category',
      label: '5. Microservices And Distributed Systems',
      items: [
        'architecture/MICROSERVICES-DISTRIBUTED-SYSTEMS',
        {
          type: 'category',
          label: 'Architecture Basics',
          items: [
            'architecture/MICROSERVICES-GENERIC',
            'architecture/DISTRIBUTED-SYSTEMS-GENERIC',
            'development/API-GATEWAY-GENERIC',
            'development/SPRING-CLOUD-GATEWAY-ADVANCED',
            'architecture/SERVICE-DISCOVERY',
            'architecture/LOAD-BALANCING-GENERIC',
            'architecture/CQRS',
          ],
        },
        {
          type: 'category',
          label: 'Consistency And Coordination',
          items: [
            'architecture/DISTRIBUTED-CONSISTENCY-CAP',
            'data/DISTRIBUTED-DATABASES',
            'reliability/DISTRIBUTED-TRANSACTIONS-LOCKS',
            {
              type: 'category',
              label: 'Locking And Work Ownership',
              items: [
                'reliability/locking/LOCKING-AND-WORK-OWNERSHIP',
                'reliability/locking/DATABASE-LOCKING-AND-CLAIMS',
                'reliability/locking/SCHEDULER-LOCKING-SHEDLOCK',
                'reliability/locking/DISTRIBUTED-LOCKS-AND-FENCING',
                'reliability/locking/PARTITION-AND-QUEUE-OWNERSHIP',
              ],
            },
            'reliability/SAGA-GENERIC',
            'reliability/OUTBOX-PATTERN',
            'reliability/INBOX-PATTERN',
            'reliability/SAGA-IMPLEMENTATION-GUIDE',
            'reliability/OUTBOX-IMPLEMENTATION-GUIDE',
          ],
        },
        {
          type: 'category',
          label: 'Reliability Patterns',
          items: [
            'reliability/RESILIENCE4J-GENERIC',
            'reliability/DISTRIBUTED-RATE-LIMITING',
            'reliability/HIGH-AVAILABILITY-SPOF',
            'reliability/DISTRIBUTED-FAILURE-CONSENSUS',
          ],
        },
        {
          type: 'category',
          label: 'Messaging',
          items: [
            'integration/APACHE-KAFKA',
          ],
        },
        'reference/DISTRIBUTED-SYSTEMS-INTERVIEW',
      ],
    },
    {
      type: 'category',
      label: '6. Security',
      items: [
        {
          type: 'category',
          label: 'Security Principles',
          items: [
            'security/principles/SECURITY-PRINCIPLES',
            'security/principles/API-SECURITY-PRINCIPLES',
            'security/principles/MICROSERVICES-SECURITY-PRINCIPLES',
            'security/principles/SERVICE-TO-SERVICE-SECURITY',
            'security/principles/SECRETS-AND-CREDENTIALS',
          ],
        },
        {
          type: 'category',
          label: 'JWT',
          items: [
            'security/jwt/JWT-FUNDAMENTALS',
            'security/jwt/JWKS-ASYMMETRIC-JWT',
            'security/jwt/JWT-CLAIMS-ROLES-SCOPES',
            'security/jwt/JWT-BEST-PRACTICES',
          ],
        },
        {
          type: 'category',
          label: 'OAuth2 And OIDC',
          items: [
            'security/oauth/OAUTH2-FUNDAMENTALS',
            'security/oauth/OAUTH2-GRANT-TYPES',
            'security/oauth/OIDC-FUNDAMENTALS',
            'security/oauth/TOKEN-LIFECYCLE',
          ],
        },
        {
          type: 'category',
          label: 'Spring Security',
          items: [
            'security/SPRING-SECURITY-GENERIC',
            'security/spring-security/AUTHENTICATION-BASICS',
            'security/spring-security/SERVLET-FILTER-CHAIN',
            'security/spring-security/JWT-JWKS-RESOURCE-SERVER',
            'security/spring-security/AUTHORIZATION-METHOD-SECURITY',
            'security/spring-security/OAUTH2-OIDC-FLOWS',
            'security/spring-security/PRODUCTION-PRACTICES',
            'security/SECURITY-IMPLEMENTATION-GUIDE',
            'security/ACCESS-REFRESH-API-KEY-IMPLEMENTATION-GUIDE',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '7. Logging And Observability',
      items: [
        'observability/LOGGING-GENERIC',
        'observability/MDC-GENERIC',
        'observability/MICROMETER-METRICS',
        'observability/PROMETHEUS',
        'observability/LOKI',
        'observability/PROMTAIL',
        'observability/GRAFANA',
        'observability/OBSERVABILITY-IMPLEMENTATION-GUIDE',
      ],
    },
    {
      type: 'category',
      label: '8. Delivery, Containers And CI/CD',
      items: [
        'operations/README',
        'operations/DEPLOYMENT-STRATEGIES',
        'operations/DOCKER',
        'operations/MINIO',
        'operations/SHOPVERSE-DOCKER',
        'operations/LOCAL-DOCKER-IMPLEMENTATION-GUIDE',
        'operations/CI-CD-AUTOMATION',
        'operations/JENKINS',
        'operations/SHOPVERSE-JENKINS',
        'operations/GITHUB-ACTIONS',
        'operations/DOCUSAURUS',
        'operations/SPRING-BOOT-ADMIN',
        'operations/OPERATIONS-CHEATSHEET',
      ],
    },
    {
      type: 'category',
      label: '9. AI, RAG And Java AI',
      collapsed: false,
      items: [
        'ai/README',
        {
          type: 'category',
          label: 'Start Here',
          collapsed: false,
          items: [
            'ai/BEGINNER-TO-ADVANCED-GUIDE',
            'ai/VISUAL-LEARNING-GUIDE',
            'ai/AI-LEARNING-PLAN',
            'ai/AI-FRAMEWORKS-FROM-ZERO',
            'ai/SPRING-AI-LANGCHAIN4J-JAVA',
          ],
        },
        {
          type: 'category',
          label: 'Core AI Concepts',
          collapsed: false,
          items: [
            'ai/LLM-GENERATIVE-AI-FUNDAMENTALS',
            'ai/API-INTEGRATION-PROMPTING',
            'ai/EMBEDDINGS-VECTOR-DB-RAG',
            'ai/ADVANCED-AI-TOPICS',
          ],
        },
        {
          type: 'category',
          label: 'Java AI',
          collapsed: false,
          items: [
            'ai/JAVA-AI-DEVELOPER-GUIDE',
            'ai/JAVA-AI-CODE-COOKBOOK',
          ],
        },
        {
          type: 'category',
          label: 'Spring AI',
          collapsed: false,
          items: [
            'ai/SPRING-AI-UMBRELLA',
            'ai/SPRING-AI-DEEP-DIVE',
          ],
        },
        {
          type: 'category',
          label: 'LangChain4j',
          collapsed: false,
          items: [
            'ai/LANGCHAIN4J-UMBRELLA',
            {
              type: 'category',
              label: 'Tutorials For Java/Spring',
              collapsed: false,
              items: [
                'ai/LANGCHAIN4J-TUTORIALS',
                'ai/LANGCHAIN4J-TUTORIAL-CHAT-MODELS',
                'ai/LANGCHAIN4J-TUTORIAL-AI-SERVICES',
                'ai/LANGCHAIN4J-TUTORIAL-TOOLS-MEMORY',
                'ai/LANGCHAIN4J-TUTORIAL-RAG',
                'ai/LANGCHAIN4J-TUTORIAL-SPRING-BOOT',
              ],
            },
            'ai/LANGCHAIN4J-DEEP-DIVE',
          ],
        },
        {
          type: 'category',
          label: 'Framework Comparison',
          collapsed: false,
          items: [
            'ai/SPRING-AI-VS-LANGCHAIN4J',
          ],
        },
        {
          type: 'category',
          label: 'Security And Guardrails',
          collapsed: false,
          items: [
            'ai/AI-SECURITY-GUARDRAILS',
          ],
        },
        {
          type: 'category',
          label: 'Shopverse Hands-on',
          collapsed: false,
          items: [
            'ai/SHOPVERSE-AI-POC-PLAN',
            'ai/HANDS-ON-LABS',
            'ai/INTERVIEW-QA',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '10. Shopverse Implementation',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Overview And Demo',
          collapsed: false,
          items: [
            'case-study/SHOPVERSE',
            'case-study/COMPLETE-DEMO',
            'case-study/SHOPVERSE-ONBOARDING-ARCHITECTURE-AUDIT',
            'reference/FEATURES-AND-DEMOS',
            'reference/CODE-CROSS-CHECK',
          ],
        },
        {
          type: 'category',
          label: 'Architecture And Services',
          items: [
            'architecture/SYSTEM-DESIGN',
            {
              type: 'category',
              label: 'Architecture Decisions',
              items: [
                'architecture/adr/gateway-discovery-config',
                'architecture/adr/kafka-choreography-saga',
                'architecture/adr/jwt-jwks-security',
                'architecture/adr/observability-stack',
              ],
            },
            'architecture/DISTRIBUTED-SYSTEMS',
            'services/SERVICE-CATALOG',
          ],
        },
        {
          type: 'category',
          label: 'API And Gateway',
          items: [
            'development/API-GUIDE',
          ],
        },
        {
          type: 'category',
          label: 'Implementation Guides',
          collapsed: false,
          items: [
            'development/API-GATEWAY-IMPLEMENTATION-GUIDE',
            'reliability/RATE-LIMITING-IMPLEMENTATION-GUIDE',
            'reliability/SAGA-IMPLEMENTATION-GUIDE',
            'reliability/OUTBOX-IMPLEMENTATION-GUIDE',
            'security/SECURITY-IMPLEMENTATION-GUIDE',
            'security/ACCESS-REFRESH-API-KEY-IMPLEMENTATION-GUIDE',
            'observability/OBSERVABILITY-IMPLEMENTATION-GUIDE',
            'operations/LOCAL-DOCKER-IMPLEMENTATION-GUIDE',
          ],
        },
        {
          type: 'category',
          label: 'Platform Infrastructure',
          collapsed: false,
          items: [
            'platform/README',
            'platform/DUPLICATE-LOGIC',
            'platform/MIGRATION-CHECKLIST',
            'platform/BEFORE-AFTER-FILES',
            'platform/CONFIG-PROPERTIES',
            'platform/TROUBLESHOOTING',
            'platform/COMMON-ERROR',
            'platform/WEB-PAGINATION',
            'platform/OBSERVABILITY-STARTER',
            'platform/SECURITY-STARTER',
            'platform/KAFKA-PARSING',
            'platform/OUTBOX-STARTER',
            'platform/KAFKA-RECOVERY-STARTER',
          ],
        },
        {
          type: 'category',
          label: 'Checkout Reliability',
          items: [
            'reliability/SAGA-OUTBOX',
            'reliability/SHOPVERSE-SAGA-CODE-FLOW',
            'reliability/TRANSACTIONS',
            'reliability/RESILIENCE4J',
          ],
        },
        {
          type: 'category',
          label: 'Security',
          items: [
            'security/JWT-OAUTH2-SPRING-SECURITY',
          ],
        },
        {
          type: 'category',
          label: 'Observability',
          items: [
            'observability/OBSERVABILITY',
            'observability/SHOPVERSE-OBSERVABILITY-OPERATIONS',
            'observability/MDC-CORRELATION-TRACING',
            'observability/STRUCTURED-LOGGING',
          ],
        },
        {
          type: 'category',
          label: 'Operations And Testing',
          items: [
            'development/TESTING',
            'development/DEBUGGING',
          ],
        },
        {
          type: 'category',
          label: 'Problems And Solutions',
          items: [
            'reliability/PROBLEMS-AND-SOLUTIONS',
            'reliability/problems/README',
            {
              type: 'category',
              label: 'Runtime Reliability Problems',
              items: [
                'reliability/problems/RUNTIME-RELIABILITY-PROBLEMS',
                'reliability/problems/runtime/INDEX-AND-LOCKING',
                'reliability/problems/runtime/DISTRIBUTED-CHECKOUT',
                'reliability/problems/runtime/QUERYABLE-ORDER-TIMELINE',
                'reliability/problems/runtime/RESOURCE-OWNERSHIP-AUTHORIZATION',
                {
                  type: 'category',
                  label: 'Reservation Expiry And Recovery',
                  items: [
                    'reliability/problems/runtime/MULTI-REPLICA-RESERVATION-EXPIRY',
                    'reliability/problems/runtime/ATOMIC-RESERVATION-CLAIM',
                    'reliability/problems/runtime/TWO-SCHEDULER-RESERVATION-EXAMPLE',
                    'reliability/problems/runtime/LATE-PAYMENT-AFTER-EXPIRY',
                  ],
                },
                'reliability/problems/runtime/IDEMPOTENT-CHECKOUT',
                'reliability/problems/runtime/CATALOG-LOOKUP-CHECKOUT',
                'reliability/problems/runtime/KAFKA-IDEMPOTENCY',
                'reliability/problems/runtime/PAYMENT-TIMEOUT-RECONCILIATION',
              ],
            },
            'reliability/problems/OUTBOX-RUNTIME-PROBLEMS',
            'reliability/problems/DOCKER-RUNTIME-IMAGE-PROBLEMS',
            'reliability/problems/DEPENDENCY-VERIFICATION-PROBLEMS',
            {
              type: 'category',
              label: 'Optimization Solutions',
              items: [
                'reliability/problems/OPTIMIZATION-SOLUTIONS',
                'reliability/problems/optimization/OPTIMIZATION-BASELINE',
                'reliability/problems/optimization/DOCKER-BUILD-CONTEXT-PLATFORM',
                'reliability/problems/optimization/ORDER-SERVICE-TEST-OPTIMIZATION',
                'reliability/problems/optimization/DOCKER-IMAGE-SIZE-OPTIMIZATION',
                'reliability/problems/optimization/JAR-SIZE-OPTIMIZATION',
                'reliability/problems/optimization/DOCKER-COMPOSE-PROFILES',
                'reliability/problems/optimization/GRADLE-DEPENDENCY-OPTIMIZATION',
                'reliability/problems/optimization/GRADLE-BUILD-PERFORMANCE',
                'reliability/problems/optimization/RUNTIME-OPTIMIZATION',
                'reliability/problems/optimization/VERIFICATION-AND-DOCUMENTATION',
              ],
            },
            'reliability/problems/PROBLEMS-SUMMARY-LINKS',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
