/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Backend Engineering Knowledge Base",
  "tagline": "Study material, production patterns, and the Shopverse case study",
  "favicon": "img/favicon.svg",
  "url": "https://taukhir.github.io",
  "baseUrl": "/shopverse/",
  "organizationName": "taukhir",
  "projectName": "shopverse",
  "customFields": {
    "analyticsDomain": "",
    "docxExportEndpoint": ""
  },
  "onBrokenLinks": "throw",
  "onBrokenAnchors": "throw",
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid",
    [
      "@easyops-cn/docusaurus-search-local",
      {
        "hashed": true,
        "language": [
          "en"
        ],
        "indexDocs": true,
        "indexBlog": false,
        "docsDir": "docs",
        "docsRouteBasePath": "/",
        "ignoreFiles": [
          {},
          {},
          {},
          {},
          {},
          {}
        ],
        "ignoreCssSelectors": [
          "pre",
          ".theme-code-block",
          ".docusaurus-mermaid-container",
          ".reading-metadata",
          "[aria-label=\"Reader actions\"]",
          "[aria-label=\"Content freshness\"]",
          "[aria-label=\"Guide details\"]",
          "[aria-labelledby=\"topics-covered-title\"]"
        ],
        "highlightSearchTermsOnTargetPage": false,
        "explicitSearchResultPath": true
      }
    ]
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "path": "docs",
          "routeBasePath": "/",
          "sidebarPath": "./sidebars.ts",
          "remarkPlugins": [
            null
          ],
          "showLastUpdateAuthor": false,
          "showLastUpdateTime": false
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5
        }
      }
    ]
  ],
  "themeConfig": {
    "metadata": [
      {
        "name": "description",
        "content": "Backend engineering guides, production patterns, and the Shopverse microservices case study."
      }
    ],
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "announcementBar": {
      "id": "reading_help_v1",
      "content": "Tip: use search to jump across the library, and click any documentation image to inspect it full size.",
      "backgroundColor": "#e6e8ff",
      "textColor": "#2f3d9e",
      "isCloseable": true
    },
    "colorMode": {
      "defaultMode": "light",
      "respectPrefersColorScheme": true,
      "disableSwitch": false
    },
    "mermaid": {
      "theme": {
        "light": "base",
        "dark": "base"
      },
      "options": {
        "fontFamily": "Inter, ui-sans-serif, system-ui, sans-serif",
        "fontSize": 15,
        "flowchart": {
          "curve": "basis",
          "htmlLabels": true,
          "nodeSpacing": 36,
          "rankSpacing": 48,
          "padding": 18,
          "useMaxWidth": true
        },
        "sequence": {
          "actorMargin": 56,
          "boxMargin": 12,
          "diagramMarginX": 24,
          "diagramMarginY": 18,
          "messageMargin": 36,
          "mirrorActors": false,
          "useMaxWidth": true
        }
      }
    },
    "navbar": {
      "title": "Backend Engineering",
      "logo": {
        "alt": "Backend Engineering Knowledge Base",
        "src": "img/favicon.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "docsSidebar",
          "position": "left",
          "label": "Study Library"
        },
        {
          "to": "/reference/LEARNING-PATH",
          "label": "Learning Path",
          "position": "left"
        },
        {
          "to": "/case-study/SHOPVERSE",
          "label": "Shopverse Case Study",
          "position": "left"
        },
        {
          "href": "https://github.com/taukhir/shopverse",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Study",
          "items": [
            {
              "label": "Learning path",
              "to": "/reference/LEARNING-PATH"
            },
            {
              "label": "Spring ecosystem",
              "to": "/spring/SPRING-ECOSYSTEM"
            },
            {
              "label": "Database engineering",
              "to": "/data/DATABASE-ENGINEERING"
            }
          ]
        },
        {
          "title": "Distributed Systems",
          "items": [
            {
              "label": "Microservices",
              "to": "/architecture/MICROSERVICES-GENERIC"
            },
            {
              "label": "Kafka",
              "to": "/integration/APACHE-KAFKA"
            },
            {
              "label": "SAGA and Outbox",
              "to": "/reliability/SAGA-GENERIC"
            }
          ]
        },
        {
          "title": "Case Study",
          "items": [
            {
              "label": "Shopverse overview",
              "to": "/case-study/SHOPVERSE"
            },
            {
              "label": "System design",
              "to": "/architecture/SYSTEM-DESIGN"
            },
            {
              "label": "Problems and solutions",
              "to": "/reliability/PROBLEMS-AND-SOLUTIONS"
            }
          ]
        }
      ],
      "copyright": "Copyright 2026 Backend Engineering Knowledge Base"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#9CDCFE",
          "backgroundColor": "#1E1E1E"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "java",
        "bash",
        "powershell",
        "yaml",
        "json",
        "sql"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 4
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "storage": {
    "type": "localStorage",
    "namespace": false
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false,
      "siteStorageNamespacing": false,
      "fasterByDefault": false,
      "mdx1CompatDisabledByDefault": false
    },
    "faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false,
      "gitEagerVcs": false
    },
    "experimental_vcs": {},
    "experimental_router": "browser"
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
